### ISSUE TITLE
"createEventInteractively" will cause immediately shut down with iOS 8.4.1 (12H321)

### ISSUE THREAD

**Issue by bau720123** [EddyVerbruggen/Calendar-PhoneGap-Plugin#213]
hi @EddyVerbruggen 
I am using PGB 5.2.0 with your latest version from npm
https://www.npmjs.com/package/cordova-plugin-calendar

this is my full example
```
var title = "title";
var newTitle = "newtitle";
var location = "location"
var notes = "notes";
var startDate = new Date(new Date().getTime());
var endDate = new Date(new Date().getTime() + 3*24*60*60*1000);
var futureDate = new Date(new Date().getTime() + 6*24*60*60*1000);
var calendarName = "mycalendar";
window.plugins.calendar.createEventInteractively(title, location, notes, startDate, endDate, success, error);
```

when in Android 4.4.2，work perfect and will show the Interactively windows
but whne in iOS 8.4.1 (12H321)，it will cause the app immediately shut down

**Comment by EddyVerbruggen** [comment]
#212 has been fixed, after which I can't reproduce this one.

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
thanks for your reply
please use these code again，copy and paste

```
function checkCalendar() 
{
var title = "title";
var newTitle = "newtitle";
var location = "location"
var notes = "notes";
var startDate = new Date(new Date().getTime());
var endDate = new Date(new Date().getTime() + 3*24*60*60*1000);
var futureDate = new Date(new Date().getTime() + 6*24*60*60*1000);
var calendarName = "mycalendar";
window.plugins.calendar.createEventInteractively(title, location, notes, startDate, endDate, success, error);
}

function success(message)
{
alert('success');
}

function error(message)
{
alert('fail');
}
```

after you use execute the "checkCalendar" function，the app will immediately shut down

**Comment by EddyVerbruggen** [comment]
@bau720123 Pasted it, no crash.. can you try to figure out where the error is on your end?

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
I just tried more again in 4.4.0 version + PGB 5.2.0 + all latest official core plugin
I use iphone 6 plus + ipad mini +  iOS 8.4.1 (12H321) = still crash when execute "createEventInteractively" and "createEventInteractivelyWithOptions" (but Android 4.4.2 is really no problem at all)

please paste again all my code
```
var title = "title";
var location = "location"
var notes = "notes";
var startDate = new Date(new Date().getTime());
var endDate = new Date(new Date().getTime() + 3*24*60*60*1000);
var calendarName = "mycalendar";
var calOptions = window.plugins.calendar.getCalendarOptions();

window.plugins.calendar.createEventInteractively(title, location, notes, startDate, endDate, success, error);
window.plugins.calendar.createEventInteractivelyWithOptions(title, location, notes, startDate, endDate, calOptions, success, error);

function success(message) { alert('success'); }
function error(message) { alert('fail'); }
```

by the way just want to ask
did you have the iOS 8.4.1 (12H321) with ipad mini or iphone plus device ?
I am still figure out what the problem is

**Comment by EddyVerbruggen** [comment]
No I have an iPhone 6 (regular) with 8.4.1.

When I comment out one of those `createEvent..` lines I have no crash.

Are you able to retrieve the crashlog? That would mean going into XCode > Window > Devices > Select your device, logs.

Do you have calendars set up and granted access to your app?

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
thanks for your reply
this is the screenshot with Xcode that when I use "createEventInteractively" (you can see the crashing keyword)
![mac os x 10 10 1-2015-08-27-13-36-40](https://cloud.githubusercontent.com/assets/5110085/9513295/f46d2f02-4cc0-11e5-8d3c-88990143f426.png)

```
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Warning>: THREAD WARNING: ['Calendar'] took '15.046875' ms. Plugin should use a background thread.
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Warning>: bool _WebTryThreadLock(bool), 0x187614b0: Tried to obtain the web lock from a thread other than the main thread or the web thread. This may be a result of calling to UIKit from a secondary thread. Crashing now...
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Notice>: 1   0x3294e7ef WebThreadLock
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Notice>: 2   0x2a364659 <redacted>
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Notice>: 3   0x17ea09 -[CDVViewController shouldAutorotateToInterfaceOrientation:]
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Notice>: 4   0xd62bd -[MainViewController shouldAutorotateToInterfaceOrientation:]
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Notice>: 5   0x17ea85 -[CDVViewController supportedInterfaceOrientations]
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Notice>: 6   0x2a0350df <redacted>
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Notice>: 7   0x2a03ca49 <redacted>
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Notice>: 8   0x2a258fcf <redacted>
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Notice>: 9   0x2a2baa31 <redacted>
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Notice>: 10  0x2688abf1 <redacted>
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Notice>: 11  0x2688ab19 <redacted>
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Notice>: 12  0x2a2ba9c7 <redacted>
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Notice>: 13  0x2a258f79 <redacted>
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Notice>: 14  0x2a3bc245 <redacted>
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Notice>: 15  0x2a3bb555 <redacted>
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Notice>: 16  0x2691dea5 <redacted>
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Notice>: 17  0x268779ed _CFXNotificationPost
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Notice>: 18  0x275db3a1 <redacted>
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Notice>: 19  0x2a0a8e31 <redacted>
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Notice>: 20  0x2a2b6795 <redacted>
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Notice>: 21  0x2a2b6e27 <redacted>
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Notice>: 22  0x2a0a7a01 <redacted>
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Notice>: 23  0x153e4b __37-[Calendar createEventInteractively:]_block_invoke
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Notice>: 24  0x35675c83 <redacted>
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Notice>: 25  0x3568286b <redacted>
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Notice>: 26  0x356838a3 <redacted>
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Notice>: 27  0x357f7d9d _pthread_wqthread
Aug 27 13:32:21 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[281] <Notice>: 28  0x357f7af0 start_wqthread
Aug 27 13:32:21 kodzutsumiteki-iPad ReportCrash[283] <Error>: task_set_exception_ports(B07, 400, D03, 0, 0) failed with error (4: (os/kern) invalid argument)
Aug 27 13:32:21 kodzutsumiteki-iPad ReportCrash[283] <Notice>: ReportCrash acting against PID 281
Aug 27 13:32:21 kodzutsumiteki-iPad ReportCrash[283] <Warning>: os_activity_diagnostic_for_pid() failed!
Aug 27 13:32:21 kodzutsumiteki-iPad ReportCrash[283] <Error>: Failed while requesting activity/breadcrumb diagnostics
Aug 27 13:32:21 kodzutsumiteki-iPad ReportCrash[283] <Notice>: Formulating crash report for process jQuerytestMobileforPhoneGapEdition[281]
Aug 27 13:32:21 kodzutsumiteki-iPad com.apple.xpc.launchd[1] (UIKitApplication:com.littlebau.phonegap[0x235b][281]) <Notice>: Service exited due to signal: Segmentation fault: 11
Aug 27 13:32:21 kodzutsumiteki-iPad SpringBoard[43] <Warning>: Application 'UIKitApplication:com.littlebau.phonegap[0x235b]' crashed.
Aug 27 13:32:21 kodzutsumiteki-iPad assertiond[58] <Warning>: pid_suspend failed for <BKNewProcess: 0x1557ee30; com.littlebau.phonegap; pid: 281; hostpid: -1>: Unknown error: -1, Unknown error: -1
Aug 27 13:32:21 kodzutsumiteki-iPad assertiond[58] <Warning>: Could not set priority of <BKNewProcess: 0x1557ee30; com.littlebau.phonegap; pid: 281; hostpid: -1> to 2, priority: No such process
Aug 27 13:32:21 kodzutsumiteki-iPad assertiond[58] <Warning>: Could not set priority of <BKNewProcess: 0x1557ee30; com.littlebau.phonegap; pid: 281; hostpid: -1> to 4096, priority: No such process
Aug 27 13:32:21 kodzutsumiteki-iPad ReportCrash[283] <Notice>: Saved report to /var/mobile/Library/Logs/CrashReporter/jQuerytestMobileforPhoneGapEdition_2015-08-27-133221_kodzutsumiteki-iPad.ips
Aug 27 13:32:26 kodzutsumiteki-iPad locationd[64] <Notice>: Gesture EnabledForTopCLient: 0, EnabledInDaemonSettings: 0
Aug 27 13:32:36 kodzutsumiteki-iPad locationd[64] <Notice>: Gesture EnabledForTopCLient: 0, EnabledInDaemonSettings: 0
```

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
well..about my above log information and screenshot
anything wrong ?

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
any...further research about my above log information and screenshot ?

**Comment by EddyVerbruggen** [comment]
No time yet..

**Comment by bau720123** [comment]
OKOK
I just ask...
thanks @EddyVerbruggen

**Comment by EddyVerbruggen** [comment]
I'd appreciate it if you would stop asking the same question in various issues in the same repository. I'm only one person and read all messages.

**Comment by bau720123** [comment]
ok...
sorry for bother
never happen again

**Comment by scurker** [comment]
Having the same issue with this on various version of iOS (7, 8), so this is definitely an issue when trying to create events interactively. 

It appears there's some inconsistency with interval variables and how the default options are created. The default options returned are...

```javascript
{
  firstReminderMinutes: 60,
  secondReminderMinutes: null,
  recurrence: null,
  recurrenceInterval: 1,
  recurrenceEndDate: null,
  calendarName: null,
  calendarId: null,
  url: null
}
```

However, `interval` and `recurrenceInterval` are used interchangeably in a couple of different places. Setting `interval` fixes the iOS crashing when using `createEventInteractivelyWithOptions` because it was originally trying to pull a nil interval value. I don't know if there's intentional reasoning behind having different variable names, but I feel that keeping interval consistent across all implementations makes the most sense.

I don't think it really matters which one is used, but rather that it should be consistent.

**Comment by bau720123** [comment]
thanks @scurker detail reply
hope @EddyVerbruggen could see it when he have free time

**Comment by EddyVerbruggen** [comment]
Hi,

The interval fix is great, merged it and will be available in 4.4.4.

Thanks!
